//This file was generated by script mkregs.py

#ifndef H_IOB_UART_SWREG_H
#define H_IOB_UART_SWREG_H

#include <stdint.h>

//register/memory address mapping
//Write Addresses
#define UART_SOFTRESET 0
#define UART_DIV 2
#define UART_TXDATA 4
#define UART_TXEN 5
#define UART_RXEN 6
//Read Addresses
#define UART_TXREADY 0
#define UART_RXDATA 4
#define UART_RXREADY 1

//register/memory data widths (bit)
//Write Register/Memory
#define UART_SOFTRESET_W 8
#define UART_DIV_W 16
#define UART_TXDATA_W 8
#define UART_TXEN_W 8
#define UART_RXEN_W 8
//Read Register/Memory
#define UART_TXREADY_W 8
#define UART_RXDATA_W 8
#define UART_RXREADY_W 8

// Base Address
void IOB_UART_INIT_BASEADDR(uint32_t addr);

// Core Setters
void IOB_UART_SET_SOFTRESET(uint8_t value);
void IOB_UART_SET_DIV(uint16_t value);
void IOB_UART_SET_TXDATA(uint8_t value);
void IOB_UART_SET_TXEN(uint8_t value);
void IOB_UART_SET_RXEN(uint8_t value);

// Core Getters
uint8_t IOB_UART_GET_TXREADY();
uint8_t IOB_UART_GET_RXDATA();
uint8_t IOB_UART_GET_RXREADY();

#endif // H_IOB_UART_SWREG_H
